# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kazbo memos
email: saita@kinoshita-lab.org
description: > hoge fuga
baseurl: "/kazbo" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kazbo
github_username:  kinoshita-lab

# Build settings
markdown: kramdown
